// Targeted by JavaCPP version 1.5.6: DO NOT EDIT THIS FILE

package org.playstrategy;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class FairyStockfish extends org.playstrategy.FairyStockfishConfig {
    static { Loader.load(); }

// Parsed from fairystockfish.h

// #ifndef FAIRYSTOCKFISH_H
// #define FAIRYSTOCKFISH_H

// #include <sstream>

// #include "misc.h"
// #include "types.h"
// #include "bitboard.h"
// #include "evaluate.h"
// #include "position.h"
// #include "search.h"
// #include "syzygy/tbprobe.h"
// #include "thread.h"
// #include "tt.h"
// #include "uci.h"
// #include "piece.h"
// #include "variant.h"
// #include "apiutil.h"

    @Namespace("fairystockfish") public static native void init();


// #endif // FAIRYSTOCKFISH_H


}
