name: Build jar for fairystockfish
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17
      - name: Build javacpp jar
        run: |
          ./gradlew publish
      - uses: actions/upload-artifact@v1
        if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev') && github.event_name == 'push'
        with:
          name: fairystockfish-0.0.1
          path: fairystockfish/build/repo/org/playstrategy/fairystockfish/
